namespace WowLauncher.Models;

using System.Text.Json.Serialization;

/// <summary>
/// Per-file client manifest (Phase 1 repair-without-redownload). Unlike <see cref="ServerManifest"/>,
/// which carries a single SHA256 for the whole client ZIP, this lists every file inside it, so
/// <see cref="Services.IClientVerifyService"/> can tell WHICH file is missing/damaged instead of
/// treating the entire 5 GB archive as one opaque blob.
///
/// Wire shape is camelCase (matches <c>ArmoryApi.cs</c>/<c>FriendsApi.cs</c>), generated by
/// <c>deploy/make-file-manifest.sh</c> from an already-extracted client tree. Entirely OPTIONAL on
/// the wire: <see cref="ManifestFile.FilesUrl"/> is null/absent unless the operator publishes one,
/// and every consumer of this type falls back to the whole-ZIP path when it is.
/// </summary>
public sealed class ClientFileManifest
{
    public int Build { get; set; }
    public string? Version { get; set; }
    public List<ClientFileEntry> Files { get; set; } = [];
}

/// <summary>One file inside the client tree. <see cref="Path"/> is relative to the install root, with
/// <c>/</c> as the separator regardless of the OS that generated the manifest (matches the ZIP-entry
/// convention <see cref="Services.DownloadService.ExtractClientAsync"/> already uses).</summary>
public sealed class ClientFileEntry
{
    public string Path { get; set; } = "";
    public long Size { get; set; }
    public string Sha256 { get; set; } = "";
}

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(ClientFileManifest))]
internal partial class ClientFileManifestJsonContext : JsonSerializerContext { }
